---
- name: Install globus, Globus Connect Server, and deplay an endpoint on host
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: "sudo to root"
    command: /usr/bin/whoami

  roles:
   - ansible-role-globus-server-setup

#?
