---
- name: Install globus, Globus Connect Server, and deplay an endpoint on host
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: "sudo to root"
    command: /usr/bin/whoami

  hosts: 
  - gridftp-servers 
  - localhost

  roles:
   - ansible-role-globus-server-setup
 
   #https://github.com/luisico/ansible-gridftp
   #- ansible-gridftp

  vars_prompt:
  - name: "endpoint_name"
    prompt: "Please enter the name of this endpoint"
  
  - name: "is_public"
    prompt: "Configure a Public endpoint? (True/False)"
#?
