---
- name: Install globus, Globus Connect Server, and deplay an endpoint on host
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: "sudo to root"
    command: /usr/bin/whoami

  #vars:
  #  endpoint_name: "gbs_endpoint"
  #  is_public: "False"

  tags:
  - testpoints
  hosts: 
  - ps-testpoints
  roles:
   - ansible-role-globus-server-setup
#?
