# Create Globus Endpoint

#- name: Configure endpoint name
# Get name from user
# http://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html

- debug:
    var: "{{ endpoint_name }}"

# Edit config file
# http://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

#- lineinfile:
#    path: /etc/globus-connect-server.conf
#    regexp: "^Name ="
    #line: 'Name = {{ endpoint_name }}'
#    line: 'Name = endpoint'

#- lineinfile:
#    path: /etc/globus-connect-server.conf
#    regexp: "^Public ="
#    #line: 'Public = {{ is_public }}'
#    line: 'Public = False'




#- name: Setup server
  #command: globus-connect-server endpoint setup "ExampleName" -c 47fb25e3-77cf-4d6e-975d-124efc6f3916 -o admin@example.org --organization "OrgName" --private
  #
#  use expect prompts
#  http://docs.ansible.com/ansible/latest/modules/expect_module.html
