# Install Globus Connect Server

#- name: Request Globus Connect Server RPM and download into local directory
#  get_url:
#    url: https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
#    dest: "{{ playbook_dir }}"

- name: Install EPEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest
  register: STDOUT
- debug:
    var: STDOUT



- name: Add Globus key to local GPG keyring
  rpm_key:
    key: https://downloads.globus.org/toolkit/gt6/stable/repo/rpm/RPM-GPG-KEY-Globus

#- name: HTTP request Globus Connect Server RPM
#  get_url:
#    url: https://downloads.globus.org/toolkit/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
#    dest: "/root/" #"{{ playbook_dir }}"

# This RPM is not getting installed properly
- name: Install Globus Connect RPM
  yum:
    name: http://downloads.globus.org/toolkit/gt6/stable/installers/repo/rpm/globus-toolkit-repo-latest.noarch.rpm
    #name: globus-connect-server-repo-latest.noarch.rpm
  register: STDOUT
- debug:
    var: STDOUT

- name: Enable Repo Globus Connect Server
  shell: yum-config-manager --enable Globus-Connect-Server-5-Stable

- name: Enable Repo Globus Toolkit
  shell: yum-config-manager --enable Globus-Toolkit-6-Stable





#- name: Request EPEL repository and download into local directory
#  get_url:
#    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    dest: "{{ playbook_dir }}"






- name: Install Prerequisite packages
  yum:
    name: yum-plugin-priorities
    state: latest
  register: STDOUT
- debug:
    var: STDOUT

- name: Install Globus Connect Server
  yum:
    name: globus-connect-server54
  register: STDOUT
- debug:
    var: STDOUT

#?
