# Get globusconnectpersonal and setup a local endpoint

- name: wget latest version
  command: wget https://s3.amazonaws.com/connect.globusonline.org/linux/stable/globusconnectpersonal-latest.tgz

- name: uncompress package
  command: tar xzf globusconnectpersonal-latest.tgz

- name: cleanup
  command: rm globusconnectpersonal-latest.tgz

# TODO: make ENDPOINT_NAME a variable
- name: create endpoint
  command: globus endpoint create --personal ENDPOINT_NAME
  register: OUTPUT
- debug:
    msg: "{{ OUTPUT.stdout_lines }}"

- name: format setup key
  command: "echo {{ OUTPUT.stdout_lines[-1].split(\" \")[-1] }}"
  register: SETUP_KEY
- debug:
    msg: "{{ SETUP_KEY }}"

- name: find globusconnectpersonal and register location as var
  find:
    paths: ./
    patterns: "globusconnectpersonal"
    recurse: yes
  register: gcp
- debug:
    msg: "{{ gcp.files[0].path }}"

# SETUP_KEY initialized in "create endpoint" task
- name: setup endpoint
  command: "{{ gcp.files[0].path }} -setup {{ SETUP_KEY }}"

# Authentication handshake with Globus

# TODO: Save output as a variable -> PythonVersion
#- name: confirm python installed and linked to $PATH
#  command: python --version
#
#- name: create symbolic link
#  command: ln -s /usr/bin/python /usr/local/bin/python2
#  when: python2 is not in PATH
#
#- name: start globus connect personal
#  command: ./globusconnectpersonal -start &

#?
